### ISSUE TITLE
Add other rules to CTP Valdiator

### ISSUE THREAD

**Issue by ashishhk** [commercetools/rmf-codegen#245]
- [ ] use of named types.   https://github.com/commercetools/rmf-codegen/issues/246
  - the Body Types should be explicit defined Types and not inline declared ones
- [x] placeholder annotation for query parameters defined.  https://github.com/commercetools/rmf-codegen/issues/247
- [x] asMap annotation for pattern properties. https://github.com/commercetools/rmf-codegen/issues/248
- [x] sdkBaseUri for server URLs defined.   https://github.com/commercetools/rmf-codegen/issues/249
- [x] date properties suffix `At` or `From`/`To` for ranges.   https://github.com/commercetools/rmf-codegen/issues/250

- [x] Implement a checker in CI pipeline (master branch) https://github.com/commercetools/clients-team-internal/issues/71

All the rules can be referened here https://wiki.commercetools.com/display/CTCLIENTS/Automate+docs+PR+reviews+-+Initial+Investigation
